v 0.1
SuperdeskWebPublisher/theme-magazine pull request #1
Opened 2017-01-09 15:00 UTC by tomaszrondio

2017-01-09 16:24 UTC, ahilles107 commented on .gitignore
> +node_modules/
Only node_modules i sass-cache should stay here, rest should go to your global .gitingnore file.

2017-01-09 16:24 UTC, ahilles107 commented on amp/amp-theme/css/amp-boilerplate-noscript.html.twig
> +<noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
missing new line at end of file (any many more other files)

2017-01-09 18:07 UTC, ahilles107 commented on views/base.html.twig
> +    {# {% container 'mainNav' with {
why it's outside of container?

2017-01-09 18:09 UTC, ahilles107 commented on views/base.html.twig
> +      google: { families: [ 'Open+Sans:300,300i,400,400i,600,600i,700,800' ] }
We need to use Open Sans? We can't use system fonts? It would improve load time a lot.

2017-01-09 18:10 UTC, ahilles107 commented on views/index.html.twig
> +	{% gimmelist article from articles|start(0)|limit(11) %}
Code indentation and formating looks very bad here. Please fix it.

2017-01-09 18:12 UTC, ahilles107 commented on views/partials/article-gallery.html.twig
> +    {% if media.renditions is iterable %}
there is new way for fetching rendition by name: http://superdesk-web-publisher.readthedocs.io/en/latest/templates_system/article_media.html

2017-01-09 18:12 UTC, ahilles107 commented on views/partials/commentBox.html.twig
> +  }
if you start block in one line - close it also like that.

2017-01-11 10:20 UTC, takeit requested changes

2017-01-11 10:20 UTC, takeit commented on theme.json
> +    "name": "swp/default-theme",
the name should be `swp/magazine-theme`

2017-01-11 12:17 UTC, tomaszrondio commented on views/base.html.twig
> +      google: { families: [ 'Open+Sans:300,300i,400,400i,600,600i,700,800' ] }
ask Backo if we need open sans. Removing it won't improve load time that much. It is loaded asynchronously and cached.

2017-01-11 12:18 UTC, tomaszrondio commented on views/partials/article-gallery.html.twig
> +    {% if media.renditions is iterable %}
that is version 0.1

2017-01-23 16:20 UTC, takeit approved these changes

2017-02-01 13:48 UTC, merged