feature image + small css fix
SuperdeskWebPublisher/theme-magazine pull request #3
Opened 2017-02-10 11:25 UTC by tomaszrondio

2017-02-10 12:52 UTC, ahilles107 requested changes
Please fix your editor issues with tabs and spaces. We use 4 spaces per tab. Fix file to use always spaces.

2017-02-10 13:03 UTC, tomaszrondio commented
in themes we always used 2 spaces per tab. Having 4 would require rewriting whole theme.

2017-02-10 13:47 UTC, ahilles107 commented
then ok, it can be 2 spaces, but use allway spaces not mixed with tabs like it's now.

2018-02-02 10:22 UTC, ahilles107 commented on views/article.html.twig
> +			{% if gimme.article.featureMedia %}
use spaces instead tabs

2018-03-27 09:59 UTC, takeit approved these changes

2018-03-27 10:00 UTC, merged